CREATE TABLE `posts` (
	`id` INT NOT NULL AUTO_INCREMENT,
	`title` VARCHAR(100) NULL DEFAULT NULL,
	`caption` VARCHAR(255) NULL DEFAULT NULL,
	`content` TEXT NULL DEFAULT NULL,
	`tags` VARCHAR(50) NULL DEFAULT NULL,
	`date` DATE NULL DEFAULT NULL,
	`category` INT NULL DEFAULT NULL,
	`image` VARCHAR(50) NULL DEFAULT NULL,
	`created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP(),
	`updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP() ON UPDATE CURRENT_TIMESTAMP(),
	PRIMARY KEY (`id`)
)
COLLATE='latin1_swedish_ci';
